### ISSUE TITLE
The name of library

### ISSUE THREAD

**Issue by selfuryon** [selfuryon/netdev#1]
I need to rename this library for avoiding collision with linux netdev. So if you have some good idea about new name - write here!

**Comment by wallies** [comment]
As this library is inspired by netmiko, either netasync or asyncnet

**Comment by selfuryon** [comment]
@wallies thank for the advice! I will think about it 👍 My first thoughts were about using the name of [star](https://en.wikipedia.org/wiki/List_of_proper_names_of_stars) :)

**Comment by wallies** [comment]
@selfuryon sounds cool. We like the look of your library, so have to started to play around with it and will submit some PRs if all goes well soon.

**Comment by selfuryon** [comment]
@wallies oh, this is good! I will be looking forward to your reviews!

**Comment by selfuryon** [comment]
I've decided to choose name `sargas`. I'm going to rename the project to `sargas` after Release v1.0

**Comment by selfuryon** [comment]
or 'santal' :D
