### ISSUE TITLE
AWS lambda not able to recognize netdev ?

### ISSUE THREAD

**Issue by anknarang** [selfuryon/netdev#25]
Hi,

This is netdev is great package. Thanks for writing.

I am writing AWS lambda function using netdev library . I zipped the package in local machine and upload to lambda layers but still not able to recognize. Anyone can tried it ?

Thanks
Ankush

**Comment by selfuryon** [comment]
Hello!
I have never tried to use netdev in a serverless scenario. Can you post an example of your code?
I'll try to do it :)

**Comment by anknarang** [comment]
I need to build the package and upload to AWS. so not related to netdev. I will keep posted if does not work.

**Comment by anknarang** [comment]
Thanks for prompt reply
