### ISSUE TITLE
What is default timeout or retry Number

### ISSUE THREAD

**Issue by anknarang** [selfuryon/netdev#30]
Hi,

what is  default timeout value to connecting to device and what is retry number if fails to connect in  one time ?

How can i change retry or timeout value ?

Thanks

**Comment by selfuryon** [comment]
Hello!
The default timeout timer is 15 second. It's a default timer for all async operations in netdev. You can modify it when you create an instance by using `timeout` [parameter](https://github.com/selfuryon/netdev/blob/b96334c2ff92715c87e1ab388fcc7d48506aa954/netdev/vendors/base.py#L28)/

I haven't the retry timer, you should manage it manually. My library only create a exception `TimeoutError`, you can use it in your own code for trying to connect several times to your devices

**Comment by anknarang** [comment]
thank you..
