### ISSUE TITLE
MikrotikRouterOS raises Attribute error during initialization

### ISSUE THREAD

**Issue by zklevsha** [selfuryon/netdev#36]
**Describe the bug**

MikrotikRouterOS during initialization raises

> AttributeError: 'MikrotikRouterOS' object has no attribute '_username'

**How to reproduce**
Run tests/test_mikrotik_routeros.py

**Root cause**
Class parent class BaseDevice stores username in dictionary  self._connect_params_dict['username']

**Possible soluton**
Replace 
self._username+= "+ct200w" with self._connect_params_dict['username'] += "+ct200w"

**Comment by selfuryon** [comment]
Related #35, resolved by that PR!
Thank you!
