### ISSUE TITLE
ASA prompt checking

### ISSUE THREAD

**Issue by romankuchin** [selfuryon/netdev#7]
Hello, netdev execution fails in case ASA is configured with non-default prompt. Like "(config)# prompt hostname priority state". There is a small fix which is not ideal, but helps to avoid exceptions in some longer prompts.

        prompt = await self._find_prompt()
        context = 'system'
        # Cut off prompt from "prompt/context"
        splitted_prompt = prompt[:-1].split('/')
        # In case prompt is "hostname/context"
        if len(splitted_prompt) == 2:
            prompt = splitted_prompt[0]
            context = splitted_prompt[1]
        # In other cases like "hostname" or "hostname/priority/state" or whatever else
        else:
            prompt = splitted_prompt[0]
        self._base_prompt = prompt
        self._current_context = context
        delimiters = map(re.escape, type(self)._delimiter_list)

After that fix module works like a charm for me!
Thank you very much for your project.

**Comment by selfuryon** [comment]
@romankuchin  Hello! Thank you for your report! I never think about changing prompt with command `prompt`. I find out that it has several params:
```
configure mode commands/options:
  cluster-unit     Display the cluster unit name in the session prompt
  context          Display the context in the session prompt (multimode only)
  domain           Display the domain in the session prompt
  hostname         Display the hostname in the session prompt
  management-mode  Display management mode
  priority         Display the priority in the session prompt
  state            Display the traffic passing state in the session prompt
```
So it can consist more than 3 part with '/' separator. I think that we can omit it all in the `_set_base_prompt` function except first part (it is usually hostname in the most cases).
I will release new code for ASA in several days after some testing :)

**Comment by selfuryon** [comment]
@romankuchin Hello! I changed this code for working with your case. Now it should just work without any workarounds. Can you test it in your environment?

**Comment by selfuryon** [comment]
Thank you for submitting successful work!
